//! AC-89 (v9.1): `pcy init` — first-run `.env` bootstrap.
//!
//! Generates a complete operator `.env` from scratch:
//!
//! * `OPEN_PINCERY_BOOTSTRAP_TOKEN` — 32 bytes from `OsRng`, hex-encoded
//!   (64 chars). The existing server reads this var; the v9.1 scope
//!   proposal called it `OPEN_PINCERY_ADMIN_SEED` but the binary already
//!   wired in `BOOTSTRAP_TOKEN` (`src/cli/mod.rs`, `pcy login`,
//!   `pcy demo`). Using the real var name keeps the generated `.env`
//!   functional; RECONCILE syncs the doc name.
//! * `OPEN_PINCERY_VAULT_KEY` — 32 bytes from `OsRng`, base64 (44
//!   chars). AES-256-GCM master key per v7 AC-40.
//! * `LLM_API_KEY` — optional, prompted hidden via `rpassword`. Blank
//!   accepted with a hint to run `pcy credential add` after first
//!   login (v9.1 AC-93 wires the in-vault path).
//! * `LLM_API_BASE_URL` — prompt with default `https://openrouter.ai/api/v1`.
//!
//! Refuses to overwrite an existing `.env` without `--force`. Sets mode
//! `0600` on Unix. Never echoes generated secret values to stdout.

use std::fs::OpenOptions;
use std::io::{self, Write};
use std::path::{Path, PathBuf};

use base64::engine::general_purpose::STANDARD as BASE64_STANDARD;
use base64::engine::Engine as _;
use rand::TryRngCore;

use crate::error::AppError;

/// Default base URL offered at the `LLM_API_BASE_URL` prompt. Resolved
/// at ITERATE per CR-v91-2.
pub const DEFAULT_LLM_BASE_URL: &str = "https://openrouter.ai/api/v1";

/// Default output path for `pcy init`.
pub const DEFAULT_OUT_PATH: &str = ".env";

/// Per-prompt callback hooks so tests can drive `init` deterministically
/// without a TTY. Production code passes `Prompts::interactive()` which
/// reads from stdin / `rpassword`.
pub struct Prompts {
    /// Prompt hidden for `LLM_API_KEY`. Return `Ok(String::new())` to
    /// indicate "skip — set up via `pcy credential add` later".
    pub llm_key: Box<dyn FnMut() -> Result<String, AppError> + Send>,
    /// Prompt visible for `LLM_API_BASE_URL`. Empty input must map to
    /// [`DEFAULT_LLM_BASE_URL`].
    pub llm_base_url: Box<dyn FnMut() -> Result<String, AppError> + Send>,
}

impl Prompts {
    /// Production prompt hooks: hidden `rpassword` for the key, stdin
    /// `read_line` for the URL.
    pub fn interactive() -> Self {
        Self {
            llm_key: Box::new(|| {
                eprintln!(
                    "Optional: paste your LLM provider API key now (hidden).\n\
                     Leave blank to add later via `pcy credential add openai_api_key`."
                );
                rpassword::prompt_password("LLM_API_KEY (hidden, optional): ")
                    .map_err(|e| AppError::Internal(format!("read LLM_API_KEY prompt: {e}")))
            }),
            llm_base_url: Box::new(|| {
                eprint!("LLM_API_BASE_URL [{DEFAULT_LLM_BASE_URL}]: ");
                io::stderr().flush().ok();
                let mut buf = String::new();
                io::stdin()
                    .read_line(&mut buf)
                    .map_err(|e| AppError::Internal(format!("read LLM_API_BASE_URL: {e}")))?;
                let trimmed = buf.trim();
                Ok(if trimmed.is_empty() {
                    DEFAULT_LLM_BASE_URL.to_string()
                } else {
                    trimmed.to_string()
                })
            }),
        }
    }
}

/// Generate 32 cryptographically secure random bytes from the OS RNG.
fn random_32() -> Result<[u8; 32], AppError> {
    let mut buf = [0u8; 32];
    rand::rngs::OsRng
        .try_fill_bytes(&mut buf)
        .map_err(|e| AppError::Internal(format!("OsRng.try_fill_bytes: {e}")))?;
    Ok(buf)
}

/// Render a strong random 64-char hex bootstrap token.
pub fn generate_bootstrap_token() -> Result<String, AppError> {
    Ok(hex::encode(random_32()?))
}

/// Render a strong random 44-char base64 vault key (32 raw bytes).
pub fn generate_vault_key() -> Result<String, AppError> {
    Ok(BASE64_STANDARD.encode(random_32()?))
}

/// Compose the `.env` body from validated inputs. Pure function — no
/// I/O, easy to unit-test.
pub fn render_env(
    bootstrap_token: &str,
    vault_key: &str,
    llm_api_key: Option<&str>,
    llm_base_url: &str,
) -> String {
    let mut out = String::with_capacity(1024);
    out.push_str(
        "# Open Pincery — operator configuration\n\
         # Generated by `pcy init`. Treat this file as a secret;\n\
         # losing OPEN_PINCERY_VAULT_KEY makes every stored\n\
         # credential unrecoverable (run `pcy backup --include-vault-key`\n\
         # before relying on the vault).\n\n",
    );
    out.push_str("DATABASE_URL=postgres://open_pincery:open_pincery@localhost:5432/open_pincery\n");
    out.push_str("OPEN_PINCERY_HOST=0.0.0.0\n");
    out.push_str("OPEN_PINCERY_PORT=8080\n\n");

    out.push_str("# Admin bootstrap secret (one-time use via `pcy login --bootstrap-token`).\n");
    out.push_str(&format!(
        "OPEN_PINCERY_BOOTSTRAP_TOKEN={bootstrap_token}\n\n"
    ));

    out.push_str("# AES-256-GCM master key for the credential vault.\n");
    out.push_str(&format!("OPEN_PINCERY_VAULT_KEY={vault_key}\n\n"));

    out.push_str("# LLM provider configuration.\n");
    out.push_str(&format!("LLM_API_BASE_URL={llm_base_url}\n"));
    match llm_api_key {
        Some(k) if !k.is_empty() => out.push_str(&format!("LLM_API_KEY={k}\n")),
        _ => {
            out.push_str("# LLM_API_KEY is unset — after `pcy login`, run:\n");
            out.push_str("#   pcy credential add openai_api_key\n");
            out.push_str("#   pcy provider add openrouter --base-url $LLM_API_BASE_URL \\\n");
            out.push_str("#     --key-from-credential openai_api_key\n");
        }
    }
    out
}

/// Print the three follow-up commands to stdout. Never includes
/// generated secret values — only the file path, which is the contract
/// with [`run`]. Surfaced as a public helper so the binary post-condition
/// is unit-testable.
pub fn next_steps_message(out_path: &Path) -> String {
    let p = out_path.display();
    format!(
        "wrote {p} (mode 0600 on Unix)\n\nNext steps:\n  1. docker compose up -d --wait\n  2. pcy login --bootstrap-token \"$(grep OPEN_PINCERY_BOOTSTRAP_TOKEN {p} | cut -d= -f2)\"\n  3. pcy doctor\n"
    )
}

/// Open the output file for write with the correct permissions.
///
/// * On Unix: opens with `O_CREAT|O_WRONLY|O_TRUNC` and mode `0o600` so
///   the file is unreadable by group/other from the moment it exists.
///   Honours `--force` via the `overwrite` flag.
/// * On Windows: opens with `create(true)` / `truncate(true)`. POSIX
///   mode bits do not apply; the file inherits parent ACL. This is
///   best-effort per AC-89 (h) and documented in `docs/onboarding.md`.
fn open_for_write(path: &Path, overwrite: bool) -> Result<std::fs::File, AppError> {
    let mut opts = OpenOptions::new();
    opts.write(true).truncate(true);
    if overwrite {
        opts.create(true);
    } else {
        opts.create_new(true);
    }
    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt;
        opts.mode(0o600);
    }
    opts.open(path).map_err(|e| match e.kind() {
        io::ErrorKind::AlreadyExists => AppError::BadRequest(format!(
            "{} already exists; pass --force to overwrite",
            path.display()
        )),
        _ => AppError::Internal(format!("open {} for write: {e}", path.display())),
    })
}

/// Entry point for the `pcy init` subcommand. Returns the path that was
/// written. Never prints generated secret values.
pub fn run(out: Option<PathBuf>, force: bool, mut prompts: Prompts) -> Result<PathBuf, AppError> {
    let out_path = out.unwrap_or_else(|| PathBuf::from(DEFAULT_OUT_PATH));

    let bootstrap_token = generate_bootstrap_token()?;
    let vault_key = generate_vault_key()?;
    let llm_key = (prompts.llm_key)()?;
    let llm_base = (prompts.llm_base_url)()?;
    let llm_key_opt = if llm_key.trim().is_empty() {
        None
    } else {
        Some(llm_key.trim())
    };
    let body = render_env(&bootstrap_token, &vault_key, llm_key_opt, llm_base.trim());

    let mut f = open_for_write(&out_path, force)?;
    f.write_all(body.as_bytes())
        .map_err(|e| AppError::Internal(format!("write {}: {e}", out_path.display())))?;
    f.sync_all().ok();
    drop(f);

    println!("{}", next_steps_message(&out_path));
    Ok(out_path)
}
